package com.iwap.domain.workflow;

public enum WorkflowEventType {
    AGENT_STARTED,
    PLAN_CREATED,
    TOOL_CALL_COMPLETED,
    VALIDATION_COMPLETED,
    VALIDATION_WARNING,
    REPORT_CREATED,
    NOTIFICATION_COMPLETED,
    APPROVAL_REQUESTED
}
